version: 2.1

executors:
  default:
    working_directory: ~/train_project
    docker:
      - image: cimg/ruby:2.7.3-node
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.34
        environment:
          MY_SQL_ALLOW_EMPTY_PASSWORD: 'true'

commands: 
  install-bundle:
    steps:
      - restore_cache:
          keys:
            - train_project-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - train_project-
      - run:
          name: Install bundle
          command: |
            bundle install
      - save_cache:
          key: train_project-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  start-my-sql:
    steps:
      - run:
          name: Start sql on url
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
  create-db:
    steps:
      - run:
          name: Create db and load schema
          command: bundle exec rails db:create db:schema:load --trace

  install-yarn:
    steps:
      - restore_cache:
          keys:
            - yarn-cache-v1-{{ checksum "yarn.lock" }}
            - yarn-cache-v1-
      - run: yarn install --cache-folder ~/.cache/yarn
      - run: bundle exec rake webpacker:compile
      - save_cache:
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  test:
    steps:
      - run:
          name: 'Ruby style check'
          command: bundle exec rubocop
      - run:
          name: 'Unit Test Rspec'
          command: bundle exec rspec --format progress
jobs:
  build:
    executor: default
    steps:
      - checkout
      - install-bundle
      - install-yarn
      - start-my-sql
      - create-db
      - test

workflows:
  version: 2
  integration:
    jobs:
      - build
