version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build: # our first job, named "build"
  docker:
    - image: cimg/ruby:2.7-node # use a tailored CircleCI docker image.
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  steps:
    - checkout # pull down our git code.
    - ruby/install-deps # use the ruby orb to install dependencies
    # use the node orb to install our packages
    # specifying that we use `yarn` and to cache dependencies with `yarn.lock`
    # learn more: https://circleci.com/docs/2.0/caching/
    - node/install-packages:
        pkg-manager: yarn
        cache-key: "yarn.lock"
